=begin
#The Selling Partner API for Amazon External Fulfillment Return Item Processing

#You can use the Amazon External Fulfillment Return Item Processing API to retrieve, track, and process return items through Amazon's External Fulfillment returns management system.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::ExternalFulfillment
  # Information about the return item.
  class ModelReturn
    # The return item's ID.
    attr_accessor :id

    # The SmartConnect identifier for where the return item was dropped for delivery.
    attr_accessor :return_location_id

    # The seller's identifier for the SKU.
    attr_accessor :merchant_sku

    # The type of return.
    attr_accessor :return_type

    # The sub-type of return.
    attr_accessor :return_sub_type

    # The total number of units in the return.
    attr_accessor :number_of_units

    # The current status of the return.
    attr_accessor :status

    # The ID of the location that fulfilled the order.
    attr_accessor :fulfillment_location_id

    attr_accessor :creation_date_time

    attr_accessor :last_updated_date_time

    attr_accessor :return_metadata

    attr_accessor :return_shipping_info

    attr_accessor :marketplace_channel_details

    attr_accessor :otp_details

    # The package delivery mode. This indicates whether the return was delivered to the seller with or without a one-time password (OTP).
    attr_accessor :package_delivery_mode

    attr_accessor :replanning_details

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'return_location_id' => :'returnLocationId',
        :'merchant_sku' => :'merchantSku',
        :'return_type' => :'returnType',
        :'return_sub_type' => :'returnSubType',
        :'number_of_units' => :'numberOfUnits',
        :'status' => :'status',
        :'fulfillment_location_id' => :'fulfillmentLocationId',
        :'creation_date_time' => :'creationDateTime',
        :'last_updated_date_time' => :'lastUpdatedDateTime',
        :'return_metadata' => :'returnMetadata',
        :'return_shipping_info' => :'returnShippingInfo',
        :'marketplace_channel_details' => :'marketplaceChannelDetails',
        :'otp_details' => :'otpDetails',
        :'package_delivery_mode' => :'packageDeliveryMode',
        :'replanning_details' => :'replanningDetails'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Object',
        :'return_location_id' => :'Object',
        :'merchant_sku' => :'Object',
        :'return_type' => :'Object',
        :'return_sub_type' => :'Object',
        :'number_of_units' => :'Object',
        :'status' => :'Object',
        :'fulfillment_location_id' => :'Object',
        :'creation_date_time' => :'Object',
        :'last_updated_date_time' => :'Object',
        :'return_metadata' => :'Object',
        :'return_shipping_info' => :'Object',
        :'marketplace_channel_details' => :'Object',
        :'otp_details' => :'Object',
        :'package_delivery_mode' => :'Object',
        :'replanning_details' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AmzSpApi::ExternalFulfillment::ModelReturn` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AmzSpApi::ExternalFulfillment::ModelReturn`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'return_location_id')
        self.return_location_id = attributes[:'return_location_id']
      end

      if attributes.key?(:'merchant_sku')
        self.merchant_sku = attributes[:'merchant_sku']
      end

      if attributes.key?(:'return_type')
        self.return_type = attributes[:'return_type']
      end

      if attributes.key?(:'return_sub_type')
        self.return_sub_type = attributes[:'return_sub_type']
      end

      if attributes.key?(:'number_of_units')
        self.number_of_units = attributes[:'number_of_units']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'fulfillment_location_id')
        self.fulfillment_location_id = attributes[:'fulfillment_location_id']
      end

      if attributes.key?(:'creation_date_time')
        self.creation_date_time = attributes[:'creation_date_time']
      end

      if attributes.key?(:'last_updated_date_time')
        self.last_updated_date_time = attributes[:'last_updated_date_time']
      end

      if attributes.key?(:'return_metadata')
        self.return_metadata = attributes[:'return_metadata']
      end

      if attributes.key?(:'return_shipping_info')
        self.return_shipping_info = attributes[:'return_shipping_info']
      end

      if attributes.key?(:'marketplace_channel_details')
        self.marketplace_channel_details = attributes[:'marketplace_channel_details']
      end

      if attributes.key?(:'otp_details')
        self.otp_details = attributes[:'otp_details']
      end

      if attributes.key?(:'package_delivery_mode')
        self.package_delivery_mode = attributes[:'package_delivery_mode']
      end

      if attributes.key?(:'replanning_details')
        self.replanning_details = attributes[:'replanning_details']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @return_type.nil?
        invalid_properties.push('invalid value for "return_type", return_type cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @fulfillment_location_id.nil?
        invalid_properties.push('invalid value for "fulfillment_location_id", fulfillment_location_id cannot be nil.')
      end

      if @last_updated_date_time.nil?
        invalid_properties.push('invalid value for "last_updated_date_time", last_updated_date_time cannot be nil.')
      end

      if @return_metadata.nil?
        invalid_properties.push('invalid value for "return_metadata", return_metadata cannot be nil.')
      end

      if @return_shipping_info.nil?
        invalid_properties.push('invalid value for "return_shipping_info", return_shipping_info cannot be nil.')
      end

      if @marketplace_channel_details.nil?
        invalid_properties.push('invalid value for "marketplace_channel_details", marketplace_channel_details cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @return_type.nil?
      return_type_validator = EnumAttributeValidator.new('Object', ['CUSTOMER', 'REJECT'])
      return false unless return_type_validator.valid?(@return_type)
      return_sub_type_validator = EnumAttributeValidator.new('Object', ['NORMAL', 'REPLACEMENT', 'EXCHANGE'])
      return false unless return_sub_type_validator.valid?(@return_sub_type)
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('Object', ['CREATED', 'CARRIER_NOTIFIED_TO_PICK_UP_FROM_CUSTOMER', 'CARRIER_OUT_FOR_PICK_UP_FROM_CUSTOMER', 'CUSTOMER_CANCELLED_PICK_UP', 'CUSTOMER_RESCHEDULED_PICK_UP', 'PICKED_FROM_CUSTOMER', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'REPLANNED', 'CUSTOMER_DROPPED_OFF', 'PARTIALLY_PROCESSED', 'PROCESSED', 'REJECTED', 'CANCELLED'])
      return false unless status_validator.valid?(@status)
      return false if @fulfillment_location_id.nil?
      return false if @last_updated_date_time.nil?
      return false if @return_metadata.nil?
      return false if @return_shipping_info.nil?
      return false if @marketplace_channel_details.nil?
      package_delivery_mode_validator = EnumAttributeValidator.new('Object', ['WITH_OTP', 'WITHOUT_OTP'])
      return false unless package_delivery_mode_validator.valid?(@package_delivery_mode)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] return_type Object to be assigned
    def return_type=(return_type)
      validator = EnumAttributeValidator.new('Object', ['CUSTOMER', 'REJECT'])
      unless validator.valid?(return_type)
        fail ArgumentError, "invalid value for \"return_type\", must be one of #{validator.allowable_values}."
      end
      @return_type = return_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] return_sub_type Object to be assigned
    def return_sub_type=(return_sub_type)
      validator = EnumAttributeValidator.new('Object', ['NORMAL', 'REPLACEMENT', 'EXCHANGE'])
      unless validator.valid?(return_sub_type)
        fail ArgumentError, "invalid value for \"return_sub_type\", must be one of #{validator.allowable_values}."
      end
      @return_sub_type = return_sub_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('Object', ['CREATED', 'CARRIER_NOTIFIED_TO_PICK_UP_FROM_CUSTOMER', 'CARRIER_OUT_FOR_PICK_UP_FROM_CUSTOMER', 'CUSTOMER_CANCELLED_PICK_UP', 'CUSTOMER_RESCHEDULED_PICK_UP', 'PICKED_FROM_CUSTOMER', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'REPLANNED', 'CUSTOMER_DROPPED_OFF', 'PARTIALLY_PROCESSED', 'PROCESSED', 'REJECTED', 'CANCELLED'])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] package_delivery_mode Object to be assigned
    def package_delivery_mode=(package_delivery_mode)
      validator = EnumAttributeValidator.new('Object', ['WITH_OTP', 'WITHOUT_OTP'])
      unless validator.valid?(package_delivery_mode)
        fail ArgumentError, "invalid value for \"package_delivery_mode\", must be one of #{validator.allowable_values}."
      end
      @package_delivery_mode = package_delivery_mode
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          return_location_id == o.return_location_id &&
          merchant_sku == o.merchant_sku &&
          return_type == o.return_type &&
          return_sub_type == o.return_sub_type &&
          number_of_units == o.number_of_units &&
          status == o.status &&
          fulfillment_location_id == o.fulfillment_location_id &&
          creation_date_time == o.creation_date_time &&
          last_updated_date_time == o.last_updated_date_time &&
          return_metadata == o.return_metadata &&
          return_shipping_info == o.return_shipping_info &&
          marketplace_channel_details == o.marketplace_channel_details &&
          otp_details == o.otp_details &&
          package_delivery_mode == o.package_delivery_mode &&
          replanning_details == o.replanning_details
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, return_location_id, merchant_sku, return_type, return_sub_type, number_of_units, status, fulfillment_location_id, creation_date_time, last_updated_date_time, return_metadata, return_shipping_info, marketplace_channel_details, otp_details, package_delivery_mode, replanning_details].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        AmzSpApi::ExternalFulfillment.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
