=begin
#Selling Partner API for Delivery Shipment Invoicing

#The Selling Partner API for Delivery Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s orders.

OpenAPI spec version: 2022-07-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.75
=end

module AmzSpApi::DeliveryByAmazon::2022_07_01
  VERSION = '0.1.0'
end
