# NOTE: Generated from https://github.com/amzn/selling-partner-api-models/tree/df0f6a4d062dc27a42952c07a681d937172e38d8/models
# NOTE: If you need to regenerate: ./pull_models.sh && ./codegen.sh=begin
#Selling Partner APIs for Fulfillment Outbound

#The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.

OpenAPI spec version: 2020-07-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::FulfillmentOutboundApiModel::ReturnItemDisposition
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReturnItemDisposition' do
  before do
    # run before each test
    @instance = AmzSpApi::FulfillmentOutboundApiModel::ReturnItemDisposition.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReturnItemDisposition' do
    it 'should create an instance of ReturnItemDisposition' do
      expect(@instance).to be_instance_of(AmzSpApi::FulfillmentOutboundApiModel::ReturnItemDisposition)
    end
  end
end
