=begin
#The Selling Partner API for External Fulfillment Inventory Management

#You can use the Amazon External Fulfillment Inventory API to manage inventory operations in Amazon's External Fulfillment network, including batch inventory updates and retrievals.

OpenAPI spec version: 2024-09-11

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

module AmzSpApi::ExternalFulfillmentInventory
  VERSION = '0.1.0'
end
