# NOTE: Generated from https://github.com/amzn/selling-partner-api-models/tree/df0f6a4d062dc27a42952c07a681d937172e38d8/models
# NOTE: If you need to regenerate: ./pull_models.sh && ./codegen.sh

=begin
#Selling Partner API for Fulfillment Inbound

#The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::FulfillmentInboundApiModelV0::LabelDownloadURL
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LabelDownloadURL' do
  before do
    # run before each test
    @instance = AmzSpApi::FulfillmentInboundApiModelV0::LabelDownloadURL.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LabelDownloadURL' do
    it 'should create an instance of LabelDownloadURL' do
      expect(@instance).to be_instance_of(AmzSpApi::FulfillmentInboundApiModelV0::LabelDownloadURL)
    end
  end
  describe 'test attribute "download_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
