# NOTE: Generated from https://github.com/amzn/selling-partner-api-models/tree/df0f6a4d062dc27a42952c07a681d937172e38d8/models
# NOTE: Spec: 
# NOTE: Spec candidates: 
# NOTE: If you need to regenerate: ./pull_models.sh && ./codegen.sh=begin
#Selling Partner API for Sales

#The Selling Partner API for Sales provides APIs related to sales performance.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

module AmzSpApi::SalesApiModel
  VERSION = '0.1.0'
end
