=begin
#Selling Partner API for Shipping

#Provides programmatic access to Amazon Shipping APIs.   **Note:** If you are new to the Amazon Shipping API, refer to the latest version of <a href=\"https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference\">Amazon Shipping API (v2)</a> on the <a href=\"https://developer-docs.amazon.com/amazon-shipping/\">Amazon Shipping Developer Documentation</a> site.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.63
=end

# Common files
require 'shipping-api-model_V0/api_client'
require 'shipping-api-model_V0/api_error'
require 'shipping-api-model_V0/version'
require 'shipping-api-model_V0/configuration'

# Models
require 'shipping-api-model_V0/models/accepted_rate'
require 'shipping-api-model_V0/models/account'
require 'shipping-api-model_V0/models/account_id'
require 'shipping-api-model_V0/models/address'
require 'shipping-api-model_V0/models/cancel_shipment_response'
require 'shipping-api-model_V0/models/city'
require 'shipping-api-model_V0/models/client_reference_id'
require 'shipping-api-model_V0/models/container'
require 'shipping-api-model_V0/models/container_item'
require 'shipping-api-model_V0/models/container_list'
require 'shipping-api-model_V0/models/container_reference_id'
require 'shipping-api-model_V0/models/container_specification'
require 'shipping-api-model_V0/models/container_specification_list'
require 'shipping-api-model_V0/models/country_code'
require 'shipping-api-model_V0/models/create_shipment_request'
require 'shipping-api-model_V0/models/create_shipment_response'
require 'shipping-api-model_V0/models/create_shipment_result'
require 'shipping-api-model_V0/models/currency'
require 'shipping-api-model_V0/models/dimensions'
require 'shipping-api-model_V0/models/error'
require 'shipping-api-model_V0/models/error_list'
require 'shipping-api-model_V0/models/event'
require 'shipping-api-model_V0/models/event_code'
require 'shipping-api-model_V0/models/event_list'
require 'shipping-api-model_V0/models/get_account_response'
require 'shipping-api-model_V0/models/get_rates_request'
require 'shipping-api-model_V0/models/get_rates_response'
require 'shipping-api-model_V0/models/get_rates_result'
require 'shipping-api-model_V0/models/get_shipment_response'
require 'shipping-api-model_V0/models/get_tracking_information_response'
require 'shipping-api-model_V0/models/label'
require 'shipping-api-model_V0/models/label_result'
require 'shipping-api-model_V0/models/label_result_list'
require 'shipping-api-model_V0/models/label_specification'
require 'shipping-api-model_V0/models/label_stream'
require 'shipping-api-model_V0/models/location'
require 'shipping-api-model_V0/models/party'
require 'shipping-api-model_V0/models/postal_code'
require 'shipping-api-model_V0/models/promised_delivery_date'
require 'shipping-api-model_V0/models/purchase_labels_request'
require 'shipping-api-model_V0/models/purchase_labels_response'
require 'shipping-api-model_V0/models/purchase_labels_result'
require 'shipping-api-model_V0/models/purchase_shipment_request'
require 'shipping-api-model_V0/models/purchase_shipment_response'
require 'shipping-api-model_V0/models/purchase_shipment_result'
require 'shipping-api-model_V0/models/rate'
require 'shipping-api-model_V0/models/rate_id'
require 'shipping-api-model_V0/models/rate_list'
require 'shipping-api-model_V0/models/retrieve_shipping_label_request'
require 'shipping-api-model_V0/models/retrieve_shipping_label_response'
require 'shipping-api-model_V0/models/retrieve_shipping_label_result'
require 'shipping-api-model_V0/models/service_rate'
require 'shipping-api-model_V0/models/service_rate_list'
require 'shipping-api-model_V0/models/service_type'
require 'shipping-api-model_V0/models/service_type_list'
require 'shipping-api-model_V0/models/shipment'
require 'shipping-api-model_V0/models/shipment_id'
require 'shipping-api-model_V0/models/shipping_promise_set'
require 'shipping-api-model_V0/models/state_or_region'
require 'shipping-api-model_V0/models/time_range'
require 'shipping-api-model_V0/models/tracking_id'
require 'shipping-api-model_V0/models/tracking_information'
require 'shipping-api-model_V0/models/tracking_summary'
require 'shipping-api-model_V0/models/weight'

# APIs
require 'shipping-api-model_V0/api/shipping_api'

module AmzSpApi::ShippingApiModelV0
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::ShippingApiModelV0.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
