=begin
#Selling Partner API for Sellers

#The [Selling Partner API for Sellers](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) (Sellers API) provides essential information about seller accounts, such as:  - The marketplaces a seller can list in - The default language and currency of a marketplace - Whether the seller has suspended listings  Refer to the [Sellers API reference](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) for details about this API's operations, data types, and schemas.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.63
=end

# Common files
require 'sellers-api-model_V0/api_client'
require 'sellers-api-model_V0/api_error'
require 'sellers-api-model_V0/version'
require 'sellers-api-model_V0/configuration'

# Models
require 'sellers-api-model_V0/models/account'
require 'sellers-api-model_V0/models/address'
require 'sellers-api-model_V0/models/business'
require 'sellers-api-model_V0/models/error'
require 'sellers-api-model_V0/models/error_list'
require 'sellers-api-model_V0/models/get_account_response'
require 'sellers-api-model_V0/models/get_marketplace_participations_response'
require 'sellers-api-model_V0/models/marketplace'
require 'sellers-api-model_V0/models/marketplace_level_attributes'
require 'sellers-api-model_V0/models/marketplace_participation'
require 'sellers-api-model_V0/models/marketplace_participation_list'
require 'sellers-api-model_V0/models/participation'
require 'sellers-api-model_V0/models/primary_contact'

# APIs
require 'sellers-api-model_V0/api/sellers_api'

module AmzSpApi::SellersApiModelV0
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::SellersApiModelV0.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
