#!/bin/bash
set -euo pipefail

# Usage: ./codegen.sh [MODELS_DIR] [LIB_DIR]

MODELS_DIR=${1:-../selling-partner-api-models/models}
LIB_DIR=${2:-lib}

# Policy: Version detection
is_versioned_api() {
  local version=$1
  [[ "$version" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]
}

# Policy: API Naming
# v0 versions get a -v0 suffix to match legacy naming.
resolve_api_name() {
  local spec_path=$1
  local version=$2
  local name
  name=$(basename "$(dirname "$spec_path")")
  
  if [[ "$version" == "v0" ]]; then
    echo "${name}-v0"
  else
    echo "$name"
  fi
}

# Policy: Module Naming
# Camelize the API name (e.g., orders-v0 -> OrdersV0)
resolve_module_name() {
  local api_name=$1
  echo "$api_name" | perl -pe 's/(^|-)./uc($&)/ge;s/-//g'
}

# Regenerate the entry point .rb file from the filesystem (deterministic sorting)
regenerate_bootstrapper() {
  local api_name=$1
  local module_name=$2
  local api_dir="${LIB_DIR}/${api_name}"
  local bootstrapper="${LIB_DIR}/${api_name}.rb"

  cat <<EOF > "$bootstrapper"
# Generated by codegen.sh
require '${api_name}/api_client'
require '${api_name}/api_error'
require '${api_name}/version'
require '${api_name}/configuration'

# Models
$(find "$api_dir/models" -name "*.rb" 2>/dev/null | sort | while read -r f; do
  m=$(basename "$f" .rb)
  echo "require '${api_name}/models/$m'"
done)

# APIs
$(find "$api_dir/api" -name "*.rb" 2>/dev/null | sort | while read -r f; do
  a=$(basename "$f" .rb)
  echo "require '${api_name}/api/$a'"
done)

module AmzSpApi::${module_name}
  class << self
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
EOF
}

process_spec() {
  local spec_file=$1
  local version
  version=$(jq -r '.info.version' "$spec_file")
  
  local api_name
  api_name=$(resolve_api_name "$spec_file" "$version")
  
  local module_name
  module_name=$(resolve_module_name "$api_name")
  
  local api_dir="${LIB_DIR}/${api_name}"

  echo "Processing $api_name ($version) from $(basename "$spec_file")..."

  # Prepare directory
  rm -rf "$api_dir"
  mkdir -p "$api_dir"
  
  # Configure
  cp config.json "$api_dir/config.json"
  perl -pi -e "s/GEMNAME/${api_name}/g" "$api_dir/config.json"
  perl -pi -e "s/MODULENAME/${module_name}/g" "$api_dir/config.json"

  # Generate
  swagger-codegen generate -i "$spec_file" -l ruby -c "$api_dir/config.json" -o "$api_dir" > /dev/null

  # Flatten structure
  if [ -d "$api_dir/lib/${api_name}" ]; then
    mv "$api_dir/lib/${api_name}/"* "$api_dir/"
  fi

  # Cleanup artifacts
  rm -rf "$api_dir/lib"
  rm -f "$api_dir/"*.gemspec
  
  # Bootstrapper
  regenerate_bootstrapper "$api_name" "$module_name"
}

# Main Loop
find "$MODELS_DIR" -name "*.json" -print0 | sort -z | while IFS= read -r -d '' spec; do
  process_spec "$spec"
done
