# NOTE: Generated from https://github.com/amzn/selling-partner-api-models/tree/df0f6a4d062dc27a42952c07a681d937172e38d8/models
# NOTE: If you need to regenerate: ./pull_models.sh && ./codegen.sh=begin
#The Selling Partner API for Amazon External Fulfillment Return Item Processing

#You can use the Amazon External Fulfillment Return Item Processing API to retrieve, track, and process return items through Amazon's External Fulfillment returns management system.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ExternalFulfillment::MarketplaceChannel
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MarketplaceChannel' do
  before do
    # run before each test
    @instance = AmzSpApi::ExternalFulfillment::MarketplaceChannel.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MarketplaceChannel' do
    it 'should create an instance of MarketplaceChannel' do
      expect(@instance).to be_instance_of(AmzSpApi::ExternalFulfillment::MarketplaceChannel)
    end
  end
  describe 'test attribute "marketplace_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "channel_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
