=begin
#The Selling Partner API for Amazon External Fulfillment Return Item Processing

#You can use the Amazon External Fulfillment Return Item Processing API to retrieve, track, and process return items through Amazon's External Fulfillment returns management system.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ExternalFulfillment::ReturnsResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReturnsResponse' do
  before do
    # run before each test
    @instance = AmzSpApi::ExternalFulfillment::ReturnsResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReturnsResponse' do
    it 'should create an instance of ReturnsResponse' do
      expect(@instance).to be_instance_of(AmzSpApi::ExternalFulfillment::ReturnsResponse)
    end
  end
  describe 'test attribute "returns"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "next_token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
