# NOTE: Generated from https://github.com/amzn/selling-partner-api-models/tree/df0f6a4d062dc27a42952c07a681d937172e38d8/models
# NOTE: Spec: 
# NOTE: Spec candidates: 
# NOTE: If you need to regenerate: ./pull_models.sh && ./codegen.sh=begin
#Selling Partner API for Direct Fulfillment Transaction Status

#The Selling Partner API for Direct Fulfillment Transaction Status provides programmatic access to a direct fulfillment vendor's transaction status.

OpenAPI spec version: 2021-12-28

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

module AmzSpApi::VendorDirectFulfillmentTransactionsApiModel
  VERSION = '0.1.0'
end
