# NOTE: Generated from https://github.com/amzn/selling-partner-api-models/tree/df0f6a4d062dc27a42952c07a681d937172e38d8/models
# NOTE: If you need to regenerate: ./pull_models.sh && ./codegen.sh=begin
#Selling Partner API for Shipment Invoicing

#The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::ShipmentInvoicingApiModel
  class PaymentMethodEnum
    CREDIT_CARD = 'CreditCard'.freeze
    DEBIT_CARD = 'DebitCard'.freeze
    PIX = 'Pix'.freeze
    BANK_SLIP = 'BankSlip'.freeze
    GIFT_CARD = 'GiftCard'.freeze
    OTHER = 'Other'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = PaymentMethodEnum.constants.select { |c| PaymentMethodEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #PaymentMethodEnum" if constantValues.empty?
      value
    end
  end
end
