=begin
#The Selling Partner API for Amazon External Fulfillment Return Item Processing

#You can use the Amazon External Fulfillment Return Item Processing API to retrieve, track, and process return items through Amazon's External Fulfillment returns management system.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.75
=end

module AmzSpApi::ExternalFulfillment::2024_09_11
  VERSION = '0.1.0'
end
