=begin
#Fulfillment Inbound API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.75
=end

module AmzSpApi::FulfillmentInboundApiModelV0
  VERSION = '0.1.0'
end
