=begin
#The Selling Partner API for External Fulfillment Inventory Management

#You can use the Amazon External Fulfillment Inventory API to manage inventory operations in Amazon's External Fulfillment network, including batch inventory updates and retrievals.

OpenAPI spec version: 2024-09-11

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::ExternalFulfillmentInventory
  class HttpMethod
    GET = 'GET'.freeze
    POST = 'POST'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = HttpMethod.constants.select { |c| HttpMethod::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #HttpMethod" if constantValues.empty?
      value
    end
  end
end
