=begin
#Selling Partner API for Sales

#The Selling Partner API for Sales provides APIs related to sales performance.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.63
=end

# Common files
require 'sales-api-model_V0/api_client'
require 'sales-api-model_V0/api_error'
require 'sales-api-model_V0/version'
require 'sales-api-model_V0/configuration'

# Models
require 'sales-api-model_V0/models/decimal'
require 'sales-api-model_V0/models/error'
require 'sales-api-model_V0/models/error_list'
require 'sales-api-model_V0/models/get_order_metrics_response'
require 'sales-api-model_V0/models/money'
require 'sales-api-model_V0/models/order_metrics_interval'
require 'sales-api-model_V0/models/order_metrics_list'

# APIs
require 'sales-api-model_V0/api/sales_api'

module AmzSpApi::SalesApiModelV0
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::SalesApiModelV0.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
