=begin
#Selling Partner API for Direct Fulfillment Shipping

#The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.

OpenAPI spec version: 2021-12-28

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.63
=end

require 'spec_helper'
require 'json'

# Unit tests for AmzSpApi::VendorDirectFulfillmentShippingApiModel::CreateContainerLabelApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CreateContainerLabelApi' do
  before do
    # run before each test
    @instance = AmzSpApi::VendorDirectFulfillmentShippingApiModel::CreateContainerLabelApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreateContainerLabelApi' do
    it 'should create an instance of CreateContainerLabelApi' do
      expect(@instance).to be_instance_of(AmzSpApi::VendorDirectFulfillmentShippingApiModel::CreateContainerLabelApi)
    end
  end

  # unit tests for create_container_label
  # Creates container (pallet) label for provided shipment package association
  # @param body Request body containing the container label data.
  # @param [Hash] opts the optional parameters
  # @return [CreateContainerLabelResponse]
  describe 'create_container_label test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
