# NOTE: Generated from https://github.com/amzn/selling-partner-api-models/tree/df0f6a4d062dc27a42952c07a681d937172e38d8/models
# NOTE: Spec: 
# NOTE: Spec candidates: 
# NOTE: If you need to regenerate: ./pull_models.sh && ./codegen.sh=begin
#Amazon Shipping API

#The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.

OpenAPI spec version: v2
Contact: swa-api-core@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::ShippingApiModel
  class IneligibilityReasonCode
    NO_COVERAGE = 'NO_COVERAGE'.freeze
    PICKUP_SLOT_RESTRICTION = 'PICKUP_SLOT_RESTRICTION'.freeze
    UNSUPPORTED_VAS = 'UNSUPPORTED_VAS'.freeze
    VAS_COMBINATION_RESTRICTION = 'VAS_COMBINATION_RESTRICTION'.freeze
    SIZE_RESTRICTIONS = 'SIZE_RESTRICTIONS'.freeze
    WEIGHT_RESTRICTIONS = 'WEIGHT_RESTRICTIONS'.freeze
    LATE_DELIVERY = 'LATE_DELIVERY'.freeze
    PROGRAM_CONSTRAINTS = 'PROGRAM_CONSTRAINTS'.freeze
    TERMS_AND_CONDITIONS_NOT_ACCEPTED = 'TERMS_AND_CONDITIONS_NOT_ACCEPTED'.freeze
    UNKNOWN = 'UNKNOWN'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = IneligibilityReasonCode.constants.select { |c| IneligibilityReasonCode::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #IneligibilityReasonCode" if constantValues.empty?
      value
    end
  end
end
