=begin
#Fulfillment Inbound API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.75
=end

# Common files
require 'fulfillment-inbound-api-model-V0/api_client'
require 'fulfillment-inbound-api-model-V0/api_error'
require 'fulfillment-inbound-api-model-V0/version'
require 'fulfillment-inbound-api-model-V0/configuration'

# Models

# APIs
require 'fulfillment-inbound-api-model-V0/api/default_api'

module AmzSpApi::FulfillmentInboundApiModelV0
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::FulfillmentInboundApiModelV0.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
