=begin
#Fulfillment Inbound API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2024-03-20

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.75
=end

# Common files
require 'fulfillment-inbound-api-model/api_client'
require 'fulfillment-inbound-api-model/api_error'
require 'fulfillment-inbound-api-model/version'
require 'fulfillment-inbound-api-model/configuration'

# Models

# APIs
require 'fulfillment-inbound-api-model/api/default_api'

module AmzSpApi::FulfillmentInboundApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::FulfillmentInboundApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
