# NOTE: Generated from https://github.com/amzn/selling-partner-api-models/tree/df0f6a4d062dc27a42952c07a681d937172e38d8/models
# NOTE: Spec: 
# NOTE: Spec candidates: 
# NOTE: If you need to regenerate: ./pull_models.sh && ./codegen.sh=begin
#Selling Partner API for Application Management

#The Selling Partner API for Application Management lets you programmatically update the client secret on registered applications.

OpenAPI spec version: 2023-11-30

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'application-management-api-model/api_client'
require 'application-management-api-model/api_error'
require 'application-management-api-model/version'
require 'application-management-api-model/configuration'

# Models
require 'application-management-api-model/models/error'
require 'application-management-api-model/models/error_list'

# APIs
require 'application-management-api-model/api/applications_api'

module AmzSpApi::ApplicationManagementApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::ApplicationManagementApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
