# NOTE: Generated from https://github.com/amzn/selling-partner-api-models/tree/df0f6a4d062dc27a42952c07a681d937172e38d8/models
# NOTE: Spec: 
# NOTE: Spec candidates: 
# NOTE: If you need to regenerate: ./pull_models.sh && ./codegen.sh=begin
#Selling Partner API for Catalog Items

#The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'catalog-items-api-model/api_client'
require 'catalog-items-api-model/api_error'
require 'catalog-items-api-model/version'
require 'catalog-items-api-model/configuration'

# Models
require 'catalog-items-api-model/models/categories'
require 'catalog-items-api-model/models/error'
require 'catalog-items-api-model/models/error_list'
require 'catalog-items-api-model/models/list_catalog_categories_response'
require 'catalog-items-api-model/models/list_of_categories'

# APIs
require 'catalog-items-api-model/api/catalog_api'

module AmzSpApi::CatalogItemsApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::CatalogItemsApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
