=begin
#Selling Partner API for Delivery Shipment Invoicing

#The Selling Partner API for Delivery Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s orders.

OpenAPI spec version: 2022-07-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.75
=end

# Common files
require 'delivery-by-amazon/api_client'
require 'delivery-by-amazon/api_error'
require 'delivery-by-amazon/version'
require 'delivery-by-amazon/configuration'

# Models
require 'delivery-by-amazon/models/blob'
require 'delivery-by-amazon/models/error'
require 'delivery-by-amazon/models/error_list'
require 'delivery-by-amazon/models/get_invoice_status_response'
require 'delivery-by-amazon/models/invoice_type'
require 'delivery-by-amazon/models/program_type'
require 'delivery-by-amazon/models/shipment_invoice_status'
require 'delivery-by-amazon/models/submit_invoice_request'
require 'delivery-by-amazon/models/submit_invoice_response'

# APIs
require 'delivery-by-amazon/api/delivery_shipment_invoice_api'

module AmzSpApi::DeliveryByAmazon
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::DeliveryByAmazon.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
