=begin
#The Selling Partner API for Transfers.

#The Selling Partner API for Transfers enables selling partners to retrieve payment methods and initiate payouts for their seller accounts. This API supports the following marketplaces: DE, FR, IT, ES, SE, NL, PL, and BE.

OpenAPI spec version: 2024-06-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'finances-api-model-transfers/api_client'
require 'finances-api-model-transfers/api_error'
require 'finances-api-model-transfers/version'
require 'finances-api-model-transfers/configuration'

# Models
require 'finances-api-model-transfers/models/assignment_type'
require 'finances-api-model-transfers/models/error'
require 'finances-api-model-transfers/models/error_list'
require 'finances-api-model-transfers/models/expiry_date'
require 'finances-api-model-transfers/models/get_payment_methods_response'
require 'finances-api-model-transfers/models/initiate_payout_request'
require 'finances-api-model-transfers/models/initiate_payout_response'
require 'finances-api-model-transfers/models/marketplace_id'
require 'finances-api-model-transfers/models/payment_method_details'
require 'finances-api-model-transfers/models/payment_method_list'
require 'finances-api-model-transfers/models/payment_method_type'
require 'finances-api-model-transfers/models/payment_method_type_list'

# APIs
require 'finances-api-model-transfers/api/default_api'

module AmzSpApi::Transfers
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::Transfers.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
