=begin
#The Selling Partner API for Finances

#The Selling Partner API for Finances provides financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.

OpenAPI spec version: 2024-06-19

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'finances-api-model-finances/api_client'
require 'finances-api-model-finances/api_error'
require 'finances-api-model-finances/version'
require 'finances-api-model-finances/configuration'

# Models
require 'finances-api-model-finances/models/amazon_pay_context'
require 'finances-api-model-finances/models/big_decimal'
require 'finances-api-model-finances/models/breakdown'
require 'finances-api-model-finances/models/breakdowns'
require 'finances-api-model-finances/models/business_context'
require 'finances-api-model-finances/models/context'
require 'finances-api-model-finances/models/contexts'
require 'finances-api-model-finances/models/currency'
require 'finances-api-model-finances/models/date'
require 'finances-api-model-finances/models/deferred_context'
require 'finances-api-model-finances/models/error'
require 'finances-api-model-finances/models/error_list'
require 'finances-api-model-finances/models/item'
require 'finances-api-model-finances/models/item_related_identifier'
require 'finances-api-model-finances/models/item_related_identifiers'
require 'finances-api-model-finances/models/items'
require 'finances-api-model-finances/models/list_transactions_response'
require 'finances-api-model-finances/models/marketplace_details'
require 'finances-api-model-finances/models/payments_context'
require 'finances-api-model-finances/models/product_context'
require 'finances-api-model-finances/models/related_identifier'
require 'finances-api-model-finances/models/related_identifiers'
require 'finances-api-model-finances/models/selling_partner_metadata'
require 'finances-api-model-finances/models/time_range_context'
require 'finances-api-model-finances/models/transaction'
require 'finances-api-model-finances/models/transactions'
require 'finances-api-model-finances/models/transactions_payload'

# APIs
require 'finances-api-model-finances/api/default_api'

module AmzSpApi::Finances
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::Finances.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
