=begin
#Selling Partner API for Direct Fulfillment Shipping

#Use the Selling Partner API for Direct Fulfillment Shipping to access a direct fulfillment vendor's shipping data.

OpenAPI spec version: 2021-12-28

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/api_client'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/api_error'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/version'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/configuration'

# Models
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/address'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/carrier_id'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/container'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/container_label'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/container_label_format'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/create_container_label_request'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/create_container_label_response'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/create_shipping_labels_request'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/customer_invoice'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/customer_invoice_list'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/decimal'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/dimensions'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/error'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/error_list'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/item'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/item_quantity'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/label_data'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/package'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/packages'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/packed_item'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/packing_slip'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/packing_slip_list'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/pagination'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/party_identification'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/shipment_confirmation'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/shipment_details'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/shipment_schedule'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/shipment_status_update'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/shipping_label'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/shipping_label_list'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/shipping_label_request'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/status_update_details'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/submit_shipment_confirmations_request'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/submit_shipment_status_updates_request'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/submit_shipping_labels_request'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/tax_registration_details'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/transaction_reference'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/vendor_container_id'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/models/weight'

# APIs
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/api/create_container_label_api'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/api/customer_invoices_api'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/api/vendor_shipping_api'
require 'vendor-direct-fulfillment-shipping-api-model-vendorDirectFulfillmentShipping_2021-12-28/api/vendor_shipping_labels_api'

module AmzSpApi::VendorDirectFulfillmentShippingApiModelVendorDirectFulfillmentShipping_20211228
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorDirectFulfillmentShippingApiModelVendorDirectFulfillmentShipping_20211228.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
