=begin
#The Selling Partner API for Amazon External Fulfillment Return Item Processing

#You can use the Amazon External Fulfillment Return Item Processing API to retrieve, track, and process return items through Amazon's External Fulfillment returns management system.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.75
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ExternalFulfillment::2024_09_11::ModelReturn
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ModelReturn' do
  before do
    # run before each test
    @instance = AmzSpApi::ExternalFulfillment::2024_09_11::ModelReturn.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ModelReturn' do
    it 'should create an instance of ModelReturn' do
      expect(@instance).to be_instance_of(AmzSpApi::ExternalFulfillment::2024_09_11::ModelReturn)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "return_location_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "merchant_sku"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "return_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["CUSTOMER", "REJECT"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.return_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "return_sub_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["NORMAL", "REPLACEMENT", "EXCHANGE"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.return_sub_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "number_of_units"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["CREATED", "CARRIER_NOTIFIED_TO_PICK_UP_FROM_CUSTOMER", "CARRIER_OUT_FOR_PICK_UP_FROM_CUSTOMER", "CUSTOMER_CANCELLED_PICK_UP", "CUSTOMER_RESCHEDULED_PICK_UP", "PICKED_FROM_CUSTOMER", "IN_TRANSIT", "OUT_FOR_DELIVERY", "DELIVERED", "REPLANNED", "CUSTOMER_DROPPED_OFF", "PARTIALLY_PROCESSED", "PROCESSED", "REJECTED", "CANCELLED"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "fulfillment_location_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "creation_date_time"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "last_updated_date_time"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "return_metadata"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "return_shipping_info"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "marketplace_channel_details"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "otp_details"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "package_delivery_mode"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["WITH_OTP", "WITHOUT_OTP"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.package_delivery_mode = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "replanning_details"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
