=begin
#The Selling Partner API for Automotive.

#The Selling Partner API for Automotive provides programmatic access to information needed by selling partners to provide compatibility information about their listed products.

OpenAPI spec version: 2024-11-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.75
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::VehiclesApiModel::2024_11_01::VehiclesResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VehiclesResponse' do
  before do
    # run before each test
    @instance = AmzSpApi::VehiclesApiModel::2024_11_01::VehiclesResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VehiclesResponse' do
    it 'should create an instance of VehiclesResponse' do
      expect(@instance).to be_instance_of(AmzSpApi::VehiclesApiModel::2024_11_01::VehiclesResponse)
    end
  end
  describe 'test attribute "pagination"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "vehicles"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
