# NOTE: Generated from https://github.com/amzn/selling-partner-api-models/tree/df0f6a4d062dc27a42952c07a681d937172e38d8/models
# NOTE: Spec: 
# NOTE: Spec candidates: 
# NOTE: If you need to regenerate: ./pull_models.sh && ./codegen.sh=begin
#Selling Partner API for Fulfillment Inbound

#The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::FulfillmentInboundApiModelV0
  class LabelPrepType
    NO_LABEL = 'NO_LABEL'.freeze
    SELLER_LABEL = 'SELLER_LABEL'.freeze
    AMAZON_LABEL = 'AMAZON_LABEL'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = LabelPrepType.constants.select { |c| LabelPrepType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #LabelPrepType" if constantValues.empty?
      value
    end
  end
end
