# NOTE: Generated from https://github.com/amzn/selling-partner-api-models/tree/df0f6a4d062dc27a42952c07a681d937172e38d8/models
# NOTE: If you need to regenerate: ./pull_models.sh && ./codegen.sh

=begin
#Selling Partner API for Delivery Shipment Invoicing

#The Selling Partner API for Delivery Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s orders.

OpenAPI spec version: 2022-07-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'date'

module AmzSpApi::DeliveryByAmazon
  class ShipmentInvoiceStatus
    PROCESSING = 'Processing'.freeze
    ACCEPTED = 'Accepted'.freeze
    ERRORED = 'Errored'.freeze
    NOT_FOUND = 'NotFound'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ShipmentInvoiceStatus.constants.select { |c| ShipmentInvoiceStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ShipmentInvoiceStatus" if constantValues.empty?
      value
    end
  end
end
