=begin
#The Selling Partner API for External Fulfillment Inventory Management

#You can use the Amazon External Fulfillment Inventory API to manage inventory operations in Amazon's External Fulfillment network, including batch inventory updates and retrievals.

OpenAPI spec version: 2024-09-11

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'external-fulfillment-externalFulfillmentInventory/api_client'
require 'external-fulfillment-externalFulfillmentInventory/api_error'
require 'external-fulfillment-externalFulfillmentInventory/version'
require 'external-fulfillment-externalFulfillmentInventory/configuration'

# Models
require 'external-fulfillment-externalFulfillmentInventory/models/actionable_error'
require 'external-fulfillment-externalFulfillmentInventory/models/batch_inventory_request'
require 'external-fulfillment-externalFulfillmentInventory/models/batch_inventory_request_list'
require 'external-fulfillment-externalFulfillmentInventory/models/batch_inventory_response'
require 'external-fulfillment-externalFulfillmentInventory/models/batch_inventory_response_list'
require 'external-fulfillment-externalFulfillmentInventory/models/error'
require 'external-fulfillment-externalFulfillmentInventory/models/error_list'
require 'external-fulfillment-externalFulfillmentInventory/models/http_method'
require 'external-fulfillment-externalFulfillmentInventory/models/http_status_line'
require 'external-fulfillment-externalFulfillmentInventory/models/inventory_request'
require 'external-fulfillment-externalFulfillmentInventory/models/inventory_request_params'
require 'external-fulfillment-externalFulfillmentInventory/models/inventory_response'
require 'external-fulfillment-externalFulfillmentInventory/models/inventory_response_body'
require 'external-fulfillment-externalFulfillmentInventory/models/marketplace_attributes'

# APIs
require 'external-fulfillment-externalFulfillmentInventory/api/batch_inventory_api'

module AmzSpApi::ExternalFulfillmentInventory
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::ExternalFulfillmentInventory.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
