=begin
#The Selling Partner API for Amazon External Fulfillment Return Item Processing

#You can use the Amazon External Fulfillment Return Item Processing API to retrieve, track, and process return items through Amazon's External Fulfillment returns management system.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'external-fulfillment-externalFulfillmentReturns/api_client'
require 'external-fulfillment-externalFulfillmentReturns/api_error'
require 'external-fulfillment-externalFulfillmentReturns/version'
require 'external-fulfillment-externalFulfillmentReturns/configuration'

# Models
require 'external-fulfillment-externalFulfillmentReturns/models/date_time'
require 'external-fulfillment-externalFulfillmentReturns/models/error'
require 'external-fulfillment-externalFulfillmentReturns/models/error_list'
require 'external-fulfillment-externalFulfillmentReturns/models/invoice_information'
require 'external-fulfillment-externalFulfillmentReturns/models/marketplace_channel'
require 'external-fulfillment-externalFulfillmentReturns/models/marketplace_channel_details'
require 'external-fulfillment-externalFulfillmentReturns/models/model_return'
require 'external-fulfillment-externalFulfillmentReturns/models/otp_details'
require 'external-fulfillment-externalFulfillmentReturns/models/replanning_details'
require 'external-fulfillment-externalFulfillmentReturns/models/return_metadata'
require 'external-fulfillment-externalFulfillmentReturns/models/return_shipping_info'
require 'external-fulfillment-externalFulfillmentReturns/models/returns_response'
require 'external-fulfillment-externalFulfillmentReturns/models/tracking_info'

# APIs
require 'external-fulfillment-externalFulfillmentReturns/api/return_retrieval_api'

module AmzSpApi::ExternalFulfillmentReturns
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::ExternalFulfillmentReturns.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
