=begin
#The Selling Partner API for Amazon External Fulfillment Shipments Processing

#You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

# Common files
require 'external-fulfillment-externalFulfillmentShipments/api_client'
require 'external-fulfillment-externalFulfillmentShipments/api_error'
require 'external-fulfillment-externalFulfillmentShipments/version'
require 'external-fulfillment-externalFulfillmentShipments/configuration'

# Models
require 'external-fulfillment-externalFulfillmentShipments/models/address'
require 'external-fulfillment-externalFulfillmentShipments/models/amount'
require 'external-fulfillment-externalFulfillmentShipments/models/cancellation'
require 'external-fulfillment-externalFulfillmentShipments/models/cancellations'
require 'external-fulfillment-externalFulfillmentShipments/models/charge'
require 'external-fulfillment-externalFulfillmentShipments/models/charge_breakup'
require 'external-fulfillment-externalFulfillmentShipments/models/charges'
require 'external-fulfillment-externalFulfillmentShipments/models/compliance_attributes'
require 'external-fulfillment-externalFulfillmentShipments/models/country_code'
require 'external-fulfillment-externalFulfillmentShipments/models/courier_supported_attributes'
require 'external-fulfillment-externalFulfillmentShipments/models/custom_attribute'
require 'external-fulfillment-externalFulfillmentShipments/models/custom_attribute_type'
require 'external-fulfillment-externalFulfillmentShipments/models/custom_channel_attribute'
require 'external-fulfillment-externalFulfillmentShipments/models/date_time'
require 'external-fulfillment-externalFulfillmentShipments/models/decimal'
require 'external-fulfillment-externalFulfillmentShipments/models/dimension'
require 'external-fulfillment-externalFulfillmentShipments/models/document'
require 'external-fulfillment-externalFulfillmentShipments/models/document_v2'
require 'external-fulfillment-externalFulfillmentShipments/models/error'
require 'external-fulfillment-externalFulfillmentShipments/models/error_list'
require 'external-fulfillment-externalFulfillmentShipments/models/gift_attributes'
require 'external-fulfillment-externalFulfillmentShipments/models/invoice_info'
require 'external-fulfillment-externalFulfillmentShipments/models/invoice_requirement'
require 'external-fulfillment-externalFulfillmentShipments/models/invoice_response'
require 'external-fulfillment-externalFulfillmentShipments/models/line_item'
require 'external-fulfillment-externalFulfillmentShipments/models/line_item_with_reason'
require 'external-fulfillment-externalFulfillmentShipments/models/marketplace_attributes'
require 'external-fulfillment-externalFulfillmentShipments/models/original_line_item'
require 'external-fulfillment-externalFulfillmentShipments/models/original_line_items'
require 'external-fulfillment-externalFulfillmentShipments/models/package'
require 'external-fulfillment-externalFulfillmentShipments/models/package_delivery_status'
require 'external-fulfillment-externalFulfillmentShipments/models/package_dimensions'
require 'external-fulfillment-externalFulfillmentShipments/models/package_line_item'
require 'external-fulfillment-externalFulfillmentShipments/models/package_line_items'
require 'external-fulfillment-externalFulfillmentShipments/models/package_ship_label'
require 'external-fulfillment-externalFulfillmentShipments/models/package_ship_label_list'
require 'external-fulfillment-externalFulfillmentShipments/models/package_status'
require 'external-fulfillment-externalFulfillmentShipments/models/package_sub_status'
require 'external-fulfillment-externalFulfillmentShipments/models/packages'
require 'external-fulfillment-externalFulfillmentShipments/models/packing_slip_requirement'
require 'external-fulfillment-externalFulfillmentShipments/models/pagination'
require 'external-fulfillment-externalFulfillmentShipments/models/party_identification_info'
require 'external-fulfillment-externalFulfillmentShipments/models/party_identification_info_list'
require 'external-fulfillment-externalFulfillmentShipments/models/piece_type'
require 'external-fulfillment-externalFulfillmentShipments/models/presence_status'
require 'external-fulfillment-externalFulfillmentShipments/models/priority'
require 'external-fulfillment-externalFulfillmentShipments/models/recommended_package'
require 'external-fulfillment-externalFulfillmentShipments/models/recommended_package_line_item'
require 'external-fulfillment-externalFulfillmentShipments/models/recommended_package_line_items'
require 'external-fulfillment-externalFulfillmentShipments/models/recommended_packages'
require 'external-fulfillment-externalFulfillmentShipments/models/replaced_shipment_info'
require 'external-fulfillment-externalFulfillmentShipments/models/requirement_level'
require 'external-fulfillment-externalFulfillmentShipments/models/sku'
require 'external-fulfillment-externalFulfillmentShipments/models/serial_number'
require 'external-fulfillment-externalFulfillmentShipments/models/ship_label_metadata'
require 'external-fulfillment-externalFulfillmentShipments/models/ship_labels_input'
require 'external-fulfillment-externalFulfillmentShipments/models/ship_labels_response'
require 'external-fulfillment-externalFulfillmentShipments/models/shipment'
require 'external-fulfillment-externalFulfillmentShipments/models/shipment_acknowledgement_request'
require 'external-fulfillment-externalFulfillmentShipments/models/shipment_info'
require 'external-fulfillment-externalFulfillmentShipments/models/shipment_line_item'
require 'external-fulfillment-externalFulfillmentShipments/models/shipment_requirements'
require 'external-fulfillment-externalFulfillmentShipments/models/shipments_response'
require 'external-fulfillment-externalFulfillmentShipments/models/shipping_info'
require 'external-fulfillment-externalFulfillmentShipments/models/shipping_options'
require 'external-fulfillment-externalFulfillmentShipments/models/shipping_options_response'
require 'external-fulfillment-externalFulfillmentShipments/models/status'
require 'external-fulfillment-externalFulfillmentShipments/models/tax'
require 'external-fulfillment-externalFulfillmentShipments/models/tax_registration_info'
require 'external-fulfillment-externalFulfillmentShipments/models/time_window'
require 'external-fulfillment-externalFulfillmentShipments/models/weight'

# APIs
require 'external-fulfillment-externalFulfillmentShipments/api/shipment_processing_api'
require 'external-fulfillment-externalFulfillmentShipments/api/shipment_retrieval_api'

module AmzSpApi::ExternalFulfillmentShipments
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::ExternalFulfillmentShipments.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
