=begin
#The Selling Partner API for External Fulfillment Inventory Management

#You can use the Amazon External Fulfillment Inventory API to manage inventory operations in Amazon's External Fulfillment network, including batch inventory updates and retrievals.

OpenAPI spec version: 2024-09-11

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ExternalFulfillmentInventory::MarketplaceAttributes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MarketplaceAttributes' do
  before do
    # run before each test
    @instance = AmzSpApi::ExternalFulfillmentInventory::MarketplaceAttributes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MarketplaceAttributes' do
    it 'should create an instance of MarketplaceAttributes' do
      expect(@instance).to be_instance_of(AmzSpApi::ExternalFulfillmentInventory::MarketplaceAttributes)
    end
  end
  describe 'test attribute "channel_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["FBA", "MFN", "DF"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.channel_name = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "marketplace_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
