=begin
#Selling Partner API for Catalog Items

#The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.75
=end

# Common files
require 'catalog-items-api-model/api_client'
require 'catalog-items-api-model/api_error'
require 'catalog-items-api-model/version'
require 'catalog-items-api-model/configuration'

# Models
require 'catalog-items-api-model/models/categories'
require 'catalog-items-api-model/models/error'
require 'catalog-items-api-model/models/error_list'
require 'catalog-items-api-model/models/list_catalog_categories_response'
require 'catalog-items-api-model/models/list_of_categories'

# APIs
require 'catalog-items-api-model/api/catalog_api'

module AmzSpApi::CatalogItemsApiModel::V0
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::CatalogItemsApiModel::V0.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
