# NOTE: Generated from https://github.com/amzn/selling-partner-api-models/tree/df0f6a4d062dc27a42952c07a681d937172e38d8/models
# NOTE: If you need to regenerate: ./pull_models.sh && ./codegen.sh

=begin
#Selling Partner API for Application Management

#The Selling Partner API for Application Management lets you programmatically update the client secret on registered applications.

OpenAPI spec version: 2023-11-30

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

module AmzSpApi::ApplicationManagementApiModel
  VERSION = '0.1.0'
end
