# NOTE: Generated from https://github.com/amzn/selling-partner-api-models/tree/df0f6a4d062dc27a42952c07a681d937172e38d8/models
# NOTE: If you need to regenerate: ./pull_models.sh && ./codegen.sh

=begin
#The Selling Partner API for Amazon External Fulfillment Return Item Processing

#You can use the Amazon External Fulfillment Return Item Processing API to retrieve, track, and process return items through Amazon's External Fulfillment returns management system.

OpenAPI spec version: 2024-09-11
Contact: marketplaceapitest@amazon.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.71
=end

require 'spec_helper'
require 'json'

# Unit tests for AmzSpApi::ExternalFulfillment::ReturnRetrievalApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReturnRetrievalApi' do
  before do
    # run before each test
    @instance = AmzSpApi::ExternalFulfillment::ReturnRetrievalApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReturnRetrievalApi' do
    it 'should create an instance of ReturnRetrievalApi' do
      expect(@instance).to be_instance_of(AmzSpApi::ExternalFulfillment::ReturnRetrievalApi)
    end
  end

  # unit tests for get_return
  # Retrieve the return item with the specified ID.
  # @param return_id The ID of the return item you want.
  # @param [Hash] opts the optional parameters
  # @return [ModelReturn]
  describe 'get_return test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_returns
  # Retrieve a list of return items. You can filter results by location, RMA ID, status, or time.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :return_location_id The SmartConnect location ID of the location from which you want to retrieve return items.
  # @option opts [String] :rma_id The RMA ID of the return items you want to list.
  # @option opts [String] :status The status of return items you want to list. You can retrieve all new return items with the &#x60;CREATED&#x60; status.
  # @option opts [String] :reverse_tracking_id The reverse tracking ID of the return items you want to list.
  # @option opts [DateTime] :created_since Return items created after the specified date are included in the response. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
  # @option opts [DateTime] :created_until Return items created before the specified date are included in the response. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
  # @option opts [DateTime] :last_updated_since Return items updated after the specified date are included in the response. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. If you supply this parameter, you must also supply &#x60;returnLocationId&#x60; and &#x60;status&#x60;.
  # @option opts [DateTime] :last_updated_until Return items whose most recent update is before the specified date are included in the response. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. If you supply this parameter, you must also supply &#x60;returnLocationId&#x60; and &#x60;status&#x60;.
  # @option opts [DateTime] :last_updated_after DEPRECATED. Use the &#x60;createdSince&#x60; parameter.
  # @option opts [DateTime] :last_updated_before DEPRECATED. Use the &#x60;createdUntil&#x60; parameter.
  # @option opts [Integer] :max_results The number of return items you want to include in the response.  **Default:** 10  **Maximum:** 100
  # @option opts [String] :next_token A token that you use to retrieve the next page of results. The response includes &#x60;nextToken&#x60; when there are multiple pages of results. To get the next page of results, call the operation with this token and include the same arguments as the call that produced the token. To get a complete list, call this operation until &#x60;nextToken&#x60; is null. Note that this operation can return empty pages.
  # @return [ReturnsResponse]
  describe 'list_returns test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
