=begin
#Fulfillment Inbound API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.75
=end

require 'spec_helper'
require 'json'

# Unit tests for AmzSpApi::FulfillmentInboundApiModelV0::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = AmzSpApi::FulfillmentInboundApiModelV0::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@instance).to be_instance_of(AmzSpApi::FulfillmentInboundApiModelV0::DefaultApi)
    end
  end

  # unit tests for test_get
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'test_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
