=begin
#Selling Partner API for Reports

#Effective **June 27, 2024**, the Selling Partner API for Reports v2020-09-04 will no longer be available and all calls to it will fail. Integrations that rely on the Reports API must migrate to [Reports v2021-06-30](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference) to avoid service disruption.

OpenAPI spec version: 2020-09-04

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.63
=end

# Common files
require 'reports-api-model_20200904/api_client'
require 'reports-api-model_20200904/api_error'
require 'reports-api-model_20200904/version'
require 'reports-api-model_20200904/configuration'

# Models
require 'reports-api-model_20200904/models/cancel_report_response'
require 'reports-api-model_20200904/models/cancel_report_schedule_response'
require 'reports-api-model_20200904/models/create_report_response'
require 'reports-api-model_20200904/models/create_report_result'
require 'reports-api-model_20200904/models/create_report_schedule_response'
require 'reports-api-model_20200904/models/create_report_schedule_result'
require 'reports-api-model_20200904/models/create_report_schedule_specification'
require 'reports-api-model_20200904/models/create_report_specification'
require 'reports-api-model_20200904/models/error'
require 'reports-api-model_20200904/models/error_list'
require 'reports-api-model_20200904/models/get_report_document_response'
require 'reports-api-model_20200904/models/get_report_response'
require 'reports-api-model_20200904/models/get_report_schedule_response'
require 'reports-api-model_20200904/models/get_report_schedules_response'
require 'reports-api-model_20200904/models/get_reports_response'
require 'reports-api-model_20200904/models/report'
require 'reports-api-model_20200904/models/report_document'
require 'reports-api-model_20200904/models/report_document_encryption_details'
require 'reports-api-model_20200904/models/report_list'
require 'reports-api-model_20200904/models/report_options'
require 'reports-api-model_20200904/models/report_schedule'
require 'reports-api-model_20200904/models/report_schedule_list'

# APIs
require 'reports-api-model_20200904/api/reports_api'

module AmzSpApi::ReportsApiModel20200904
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::ReportsApiModel20200904.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
