=begin
#Selling Partner API for Catalog Items

#The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.

OpenAPI spec version: v0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.63
=end

# Common files
require 'catalog-items-api-model_V0/api_client'
require 'catalog-items-api-model_V0/api_error'
require 'catalog-items-api-model_V0/version'
require 'catalog-items-api-model_V0/configuration'

# Models
require 'catalog-items-api-model_V0/models/asin_identifier'
require 'catalog-items-api-model_V0/models/attribute_set_list'
require 'catalog-items-api-model_V0/models/attribute_set_list_type'
require 'catalog-items-api-model_V0/models/categories'
require 'catalog-items-api-model_V0/models/creator_type'
require 'catalog-items-api-model_V0/models/decimal_with_units'
require 'catalog-items-api-model_V0/models/dimension_type'
require 'catalog-items-api-model_V0/models/error'
require 'catalog-items-api-model_V0/models/error_list'
require 'catalog-items-api-model_V0/models/get_catalog_item_response'
require 'catalog-items-api-model_V0/models/identifier_type'
require 'catalog-items-api-model_V0/models/image'
require 'catalog-items-api-model_V0/models/item'
require 'catalog-items-api-model_V0/models/item_list'
require 'catalog-items-api-model_V0/models/language_type'
require 'catalog-items-api-model_V0/models/list_catalog_categories_response'
require 'catalog-items-api-model_V0/models/list_catalog_items_response'
require 'catalog-items-api-model_V0/models/list_matching_items_response'
require 'catalog-items-api-model_V0/models/list_of_categories'
require 'catalog-items-api-model_V0/models/price'
require 'catalog-items-api-model_V0/models/relationship_list'
require 'catalog-items-api-model_V0/models/relationship_type'
require 'catalog-items-api-model_V0/models/sales_rank_list'
require 'catalog-items-api-model_V0/models/sales_rank_type'
require 'catalog-items-api-model_V0/models/seller_sku_identifier'

# APIs
require 'catalog-items-api-model_V0/api/catalog_api'

module AmzSpApi::CatalogItemsApiModelV0
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::CatalogItemsApiModelV0.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
